version: '3.6'

volumes:
   mysqlccsa45604264:
   backupccsa45604264:
   nextcloudccsa45604264:

services:
   servicio_mysql_ccsa45604264:
      image: mysql
      environment:
          MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
          MYSQL_DATABASE: '${MYSQL_DATABASE}'
          MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
          MYSQL_USER: '${MYSQL_USER}'
      ports:
         - "3306"
      expose:
         - "3306"
      volumes:
         - "mysqlccsa45604264:/var/lib/mysql:rw"
         - "backupccsa45604264:/var/lib/backup:rw"
      restart: on-failure

   # Usar con: docker-compose up --scale servicio_nextcloud_ccsa45604264=2
   servicio_nextcloud_ccsa45604264:
      image: nextcloud
      restart: on-failure
      ports:
         - "80"
      volumes:
         - "nextcloudccsa45604264:/var/www/html"
      environment:
         - MYSQL_DATABASE=${MYSQL_DATABASE}
         - MYSQL_USER=${MYSQL_USER}
         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
         - MYSQL_HOST=servicio_mysql_ccsa45604264
         - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
         - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      links:
         - servicio_mysql_ccsa45604264
      depends_on:
         - servicio_mysql_ccsa45604264

   servicio_ldap_ccsa45604264:
      image: larrycai/openldap
      ports:
         - "389"
      environment:
         - LDAP_ADMIN_USERNAME=ldroot
         - LDAP_ADMIN_PASSWORD=ldpassroot
      restart: on-failure
      depends_on:
         - servicio_mysql_ccsa45604264
         - servicio_nextcloud_ccsa45604264

   servicio_nginx_ccsa45604264:
      image: nginx
      volumes:
         - ./templates:/etc/nginx/templates
      ports:
         - "31029:80"
      volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      restart: on-failure
      links:
         - servicio_nextcloud_ccsa45604264
      depends_on:
         - servicio_mysql_ccsa45604264
         - servicio_nextcloud_ccsa45604264
         - servicio_ldap_ccsa45604264
